POST  http://localhost:3000/api/services
Content-Type: application/json

{
    "name": "algum serviço 2",
    "description": "alguma descrição",
    "price": 1600,
    "image": "https://plus.unsplash.com/premium_photo-1716138192476-f34e85ad43c2?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###
GET http://localhost:3000/api/services


###
GET http://localhost:3000/api/services/67447ce2925cbb4f9e553e72


###
DELETE http://localhost:3000/api/services/67447ce2925cbb4f9e553e72


###
put  http://localhost:3000/api/services/6740ae1fc62e30617263eea0
Content-Type: application/json

{
    "name": "testando atualização",
    "description": "alguma descrição",
    "price": 2050,
    "image": "https://plus.unsplash.com/premium_photo-1716138192476-f34e85ad43c2?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}


###

POST http://localhost:3000/api/parties
Content-Type: application/json

{
    "title": "Meu Evento",
    "author": "Davi",
    "description": "Uma festa de aniversário",
    "budget": 6000,
    "image": "https://plus.unsplash.com/premium_photo-1716138192476-f34e85ad43c2?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "alguma descrição",
            "price": 3000,
            "image": "https://plus.unsplash.com/premium_photo-1716138192476-f34e85ad43c2?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },

        {
            "name": "algum serviço 2",
            "description": "alguma descrição",
            "price": 1600,
            "image": "https://plus.unsplash.com/premium_photo-1716138192476-f34e85ad43c2?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        }
    ]
}

###

GET http://localhost:3000/api/parties

###

GET  http://localhost:3000/api/parties/6745167816df0bcff0ad3330


###
DELETE http://localhost:3000/api/parties/6745167816df0bcff0ad3330


###
put http://localhost:3000/api/parties/6744f3dcd42a632f1a8bf667

Content-Type: application/json

{
    "title": "Testando update",
    "author": "Telma",
    "description": "Uma festa de aniversário",
    "budget": 6000,
    "image": "https://plus.unsplash.com/premium_photo-1716138192476-f34e85ad43c2?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "services": [
        {
            "name": "Algum serviço 1",
            "description": "alguma descrição",
            "price": 3000,
            "image": "https://plus.unsplash.com/premium_photo-1716138192476-f34e85ad43c2?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        },

        {
            "name": "algum serviço 2",
            "description": "alguma descrição",
            "price": 1600,
            "image": "https://plus.unsplash.com/premium_photo-1716138192476-f34e85ad43c2?q=80&w=3870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        }
    ]
}